
### get all payment methods
GET http://localhost:3000/api/paymentmethod


### get one payment method
GET http://localhost:3000/api/paymentmethod/f47ac10b-58cc-4372-a567-0e02b2c3d479

### create a new payment method
POST http://localhost:3000/api/paymentmethod
Content-Type: application/json

{
  "type" : "Debito"
}


### update a payment method (PUT - full, idempotent resource)
PUT http://localhost:3000/api/paymentmethod/f47ac10b-58cc-4372-a567-0e02b2c3d479
Content-Type: application/json

{
  "type" : "Credito"
}

### update a payment method (PATCH - partial resource)
PATCH http://localhost:3000/api/paymentmethod/f47ac10b-58cc-4372-a567-0e02b2c3d479
Content-Type: application/json

{
  "type": "efectivo"
}

### delete a payment method
DELETE http://localhost:3000/api/paymentmethod/f47ac10b-58cc-4372-a567-0e02b2c3d479