
### obtener todos los Tipos de Entrada
GET http://localhost:3000/api/tipoentrada


### obtener un Tipo Entrada
GET http://localhost:3000/api/tipoentrada/4f5b2b31-c2a9-4f7f-a2d8-7c4fe2d3cc91

### crear un nuevo Tipo de Entrada
POST http://localhost:3000/api/tipoentrada
Content-Type: application/json

{
    "cantidad": "2",
    "ubicacion":"Popular",
    "esNumerada":"false"
}


### modificar un Tipo de Entrada (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/tipoentrada/4f5b2b31-c2a9-4f7f-a2d8-7c4fe2d3cc91
Content-Type: application/json

{
    "cantidad": "1",
    "ubicacion":"Platea",
    "esNumerada":"true"
}

### modificar un Tipo de Entrada (PATCH - recurso parcial)
PATCH http://localhost:3000/api/tipoentrada/4f5b2b31-c2a9-4f7f-a2d8-7c4fe2d3cc91
Content-Type: application/json

{
  "cantidad": "0"
}

### borrar un tipo de entrada
DELETE http://localhost:3000/api/tipoentrada/4f5b2b31-c2a9-4f7f-a2d8-7c4fe2d3cc91