
### get all Organizers
GET http://localhost:3000/api/organizer


### get one Organizer
GET http://localhost:3000/api/organizer/4

### create a new Organizer
POST http://localhost:3000/api/organizer
Content-Type: application/json

{
  "firstName": "Juan",
  "lastName": "Perez",
  "email": "jperez@example.com",
  "identityDocument": "55555",
  "password": "juancito"
}


### update an Organizer (PUT - full, idempotent resource)
PUT http://localhost:3000/api/organizer/4
Content-Type: application/json

{
  "firstName": "Juancito",
  "lastName": "Perez",
  "email": "juan.perez@example.com",
  "identityDocument": "12345678",
  "password": "contrasena123"
}

### update an Organizer (PATCH - partial resource)
PATCH http://localhost:3000/api/organizer/4
Content-Type: application/json

{
  "firstName": "Juancho"
}

### delete an Organizer
DELETE http://localhost:3000/api/organizer/4